//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        public int box_id { get; set; }
        public int comp_id { get; set; }
        public int box_ext_id { get; set; }
        public string box_name { get; set; }
        public string aisle { get; set; }
        public string section { get; set; }
        public string brow { get; set; }
        public string bcolumn { get; set; }
    }
}
