//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public int comp_id { get; set; }
        public string access { get; set; }
    }
}
