//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string owner { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public string phone { get; set; }
        public byte barcode { get; set; }
        public byte inactive { get; set; }
    }
}
