//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int doc_id { get; set; }
        public int comp_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string doc_name { get; set; }
        public string url { get; set; }
        public int num_pages { get; set; }
        public System.DateTime date { get; set; }
        public string uploaded_by { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public string deleted_by { get; set; }
    }
}
