//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int patient_id { get; set; }
        public int comp_id { get; set; }
        public string pext_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string physician { get; set; }
        public string box { get; set; }
        public string ssn { get; set; }
    }
}
