//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDocScan.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartDocScanEntities : DbContext
    {
        public SmartDocScanEntities()
            : base("name=SmartDocScanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<box> boxes { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usersinfo> usersinfoes { get; set; }
    }
}
